### ISSUE TITLE
Layout Problems

### ISSUE THREAD

**Issue by marianbreitmeyer** [TylerBarnes/gatsby-plugin-transition-link#29] opened 2019-01-06 12:12 UTC
Hey,
just started to integrate transitionLink in the Gatsby Starter to play around with it. But I can't get it to work. I always have "double layouts" in my site. I think the config part doesn't work. Any idea how to fix this or where my mistake is?

--> https://github.com/marianbreitmeyer/portfolio-site

<img width="1426" alt="bildschirmfoto 2019-01-06 um 13 11 28" src="https://user-images.githubusercontent.com/14787628/50735796-ae71f480-11b4-11e9-9179-4f623f1a6b15.png">

**Comment by marianbreitmeyer** [comment] 2019-01-06 17:45
If I just ad `gatsby-plugin-transition-link` in the Gatsby config, it works fine. But I don't think that's the correct way, isn't it?

**Comment by TylerBarnes** [comment] 2019-01-06 19:36
Hey @marianbreitmeyer , thanks for using transition link!
The reason is that you're including your layout component twice. You've added it to the plugin options and you're also manually wrapping your layout around your pages.
https://github.com/marianbreitmeyer/portfolio-site/blob/master/src/pages/index.js
https://github.com/marianbreitmeyer/portfolio-site/blob/master/gatsby-config.js

If your remove `<Layout>` from your page you should be good.

**Comment by marianbreitmeyer** [comment] 2019-01-06 19:42
Hey, thanks for the answer. Makes totally sense. But now the footer is directly under the header. So the Layout is broken.

**Comment by marianbreitmeyer** [comment] 2019-01-06 19:44
Sorry, that was an issue with position: absolute. Everything works fine now. Thanks a lot :)

**Comment by TylerBarnes** [comment] 2019-01-06 19:45
You're welcome! Open an issue any time you're having trouble. Always happy to help out.

**Comment by marianbreitmeyer** [comment] 2019-01-06 19:55
Just saw, that the div causing the trouble is the tl-wrapper which refers to the transitionLink wrapper, right? Is there a way to make this relative?

**Comment by TylerBarnes** [comment] 2019-01-06 20:01
No, this needs to be absolute for pages to overlay each other during transition. One sec, I'm going to check this out a bit more, I cloned your project.

**Comment by TylerBarnes** [comment] 2019-01-06 20:17
Ok, for now you can add your footer to pages instead of your layout and it will display properly. 
A couple other people were having issues with the transition wrapper being `position: absolute;` so I'm going to find a more permanent solution. It's a bit tricky because we want the pages to be on top of each other during animation but we also want the footer to get pushed down by the page contents.
Expect a more permanent fix for this in the next minor release.

**Comment by aamorozov** [comment] 2019-01-07 06:41
I've been working this around this so far by explicitly passing `position: relative` in imgStyle prop so they appear correctly.

**Comment by TylerBarnes** [comment] 2019-01-07 17:49
@aamorozov thanks for the feedback. This is added so that the page doesn't continually jump to the top while developing a site. I have a few plugin options I'm going to be adding that I'm working on and I'm thinking now I'll also add an option to disable the min height wrapper. Out of curiousity can you explain what kind of layout issue you were having?

**Comment by aamorozov** [comment] 2019-01-07 17:52
It was calculating the min-height correctly for some of the pages but some of them had an excessive height hence there was a white space area at the bottom of the page, below the actual content. That's been the only layout issue I've had so far. I haven't noticed the jumpiness after forcing the min-height yet

**Comment by TylerBarnes** [comment] 2019-01-07 17:55
@aamorozov thanks! since I'm going to be spending some time on this part of the plugin soon it's good to know the types of issues people have around it. I'll add an option to disable that and also see if I can reproduce that issue while I'm in there.

**Comment by TylerBarnes** [comment] 2019-01-12 03:00
hey @marianbreitmeyer and @aamorozov , I have a beta release out which should solve your problems.
Pages are no longer `position: absolute;` so a footer in your layout component will work.
This also means there's no need for the min-height page wrapper so I've removed that.
If you have time to try it out you can install with `npm i gatsby-plugin-transition-link@1.5.0-beta.1` or `yarn add gatsby-plugin-transition-link@1.5.0-beta.1`

**Comment by aamorozov** [comment] 2019-01-13 18:11
Hi @TylerBarnes ! The 1.5.0-beta.1 throws an error on `pageMinHeight`. Looks like you've removed the funciton but it's still being referenced here https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/fixing-tl-wrapper-issues/src/components/TransitionHandler.js#L12

```
  Error: ./node_modules/gatsby-plugin-transition-link/components/TransitionHandler.js
  Module not found: Error: Can't resolve '../functions/pageMinHeight' in './node_modules/gatsby-plugin-transition-link/components'
  resolve '../functions/pageMinHeight' in './node_modules/gatsby-plugin-transition-link/components'
    using description file: ./node_modules/gatsby-plugin-transition-link/package.json (relative path: ./components)
      using description file: ./node_modules/gatsby-plugin-transition-link/package.json (relative path: ./functions/pageMinHeight)
        no extension
          ./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight doesn't exist
        .mjs
         ./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.mjs doesn't exist
        .js
          ./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.js doesn't exist
        .jsx
          ./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.jsx doesn't exist
        .wasm
          ./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.wasm doesn't exist
        .json
          ./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.json doesn't exist
        as directory
          ./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight doesn't exist
  [./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight]
  [./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.mjs]
  [./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.js]
  [./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.jsx]
  [./frontend/node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.wasm]
  [./node_modules/gatsby-plugin-transition-link/functions/pageMinHeight.json]
   @ ./node_modules/gatsby-plugin-transition-link/components/TransitionHandler.js 34:44-81
   @ ./node_modules/gatsby-plugin-transition-link/wrap-page.js
   @ ./node_modules/gatsby-plugin-transition-link/gatsby-ssr.js
   @ ./.cache/api-runner-ssr.js
   @ ./.cache/develop-static-entry.js
```

**Comment by TylerBarnes** [comment] 2019-01-13 18:53
@aamorozov oops! Embarassing. 😂This is why I need to get some tests set up sooner than later.
Must've been a quirk of `yarn link` that it was working for me.
`1.5.0-beta.3` fixes this oversight. Thanks @aamorozov

**Comment by aamorozov** [comment] 2019-01-14 14:55
Looks like the height issue is fixed in 1.5.0-beta.3 - thank you for the update! @TylerBarnes !

**Comment by TylerBarnes** [comment] 2019-01-28 21:43
closing this for now as a duplicate of #27

**Closed by TylerBarnes** 2019-01-28 21:43 UTC
Labels: bug

**Comment by thundernixon** [comment] 2019-02-16 21:21
I made a huge issue report, then finally figured out this really was the fix I needed. 😄

Maybe, potentially, it would be worth adding a note at "Usage with gatsby-plugin-layout
" in https://transitionlink.tylerbarnes.ca/docs/installation/? Something simple, like:

> Note: when you add a layout component option, be sure to not duplicate this component in your pages or you will end up with the layout nested inside itself.

**Comment by TylerBarnes** [comment] 2019-02-16 21:46
Glad to hear you sorted it out and thanks for the suggestion! I've added your note to the page.

**Comment by thundernixon** [comment] 2019-02-16 21:48
Amazing, thanks!

**Comment by lborg019** [comment] 2020-04-30 07:09
My `<div class="tl-edges">` was giving me issues too. I needed its width to be wider in order for inherited divs to behave nicely.

I do have a global.scss file in my project (using gatsby-plugin-sass), so I decided to create a 
`div.tl-edges { width: 100% }` class in order to override my customization it and it worked! I am not sure how this would impact on performance for more complex changes but it worked out nicely for me. It is likely this would also work for the tl-wrapper class div.

Hope it helps! 😄

**Comment by wispyco** [comment] 2020-07-15 17:28
My <div class="tl-edges"> was giving me a overflow hidden, and I needed it to be overflow initial at least the fixed it for me. You can see the overide here https://thingsarenotastheyseem.com/
