### ISSUE TITLE
Example for partial transitions/animating various elements

### ISSUE THREAD

**Issue by MartinConde** [TylerBarnes/gatsby-plugin-transition-link#12] opened 2018-11-22 04:30 UTC
First of all thanks a lot for this plugin!:) just found it browsing on mobile so excuse me if I am overlooking something.

Could you add an example where different elements of a page get their own transitions? (Instead of the whole Page as one)

**Comment by TylerBarnes** [comment] 2018-11-22 05:02
Hey @MartinConde thanks for the interest!

You can check out the examples page at https://gatsby-plugin-transition-link.netlify.com/
Check the second from the bottom link on the home page. All the links do something different if you click around. This plugin is built specifically for the use case you're asking about and I've tried to make it as easy / powerful as possible. My intention is that I want to use this make an awwwards.com style site. I'm currently working on a documentation site with clearer explanations and examples as well as a blog post for gatsbyjs.org which will have examples specific to this question.

To do what you're asking, you could either use gsap to do very complex looking animations (check the examples above as well as the readme) or you could use something like react-spring or react-pose and wrap individual pieces of the site in `<TransitionState />` components. Check #5 for usage with the latter types of animation libraries. The example at #5 is very simple but if you were to wrap a lot of components that way you could do more complex type transitions.

Stay tuned at #3 for more info. Closing this as a duplicate of that issue.

**Closed by TylerBarnes** 2018-11-22 05:02 UTC
