### ISSUE TITLE
Initial page content remains displayed as cover slides out of view, only vanishing after the transition is completed

### ISSUE THREAD

**Issue by NikkiGom** [TylerBarnes/gatsby-plugin-transition-link#84] opened 2019-05-06 10:26 UTC
Hello! I'm trying to use AniLink (the cover option) in my project, but keep getting this funny bug.

The problem is that the initial page remains for a split second, even as the cover slides out of view. It overlaps the newly active page for a split second before vanishing. I think that the initial page content remains until the whole transition is complete. I'm not sure why this is happening.. how can I make sure that the previously active page content vanishes before the new active page displays?

here is a link to my sandbox: https://codesandbox.io/embed/m7z386ll6x. If you click on the 'Go to page 2 transition link' on the index page, you can see the bug in action :). Once you click on the link, the blue cover slides across the page. As the cover slides out of view, for a split second you will still see all the text content from the index page overlapping the new content of page 2.

**Comment by NikkiGom** [comment] 2019-05-06 10:54
Woops, sorry I closed this issue by accident! Just re-opened it

**Comment by andrwrbnsn** [comment] 2019-05-08 20:44
I'm encountering a similar issue using anime.js to animate the transition, when I click a `<TransitionLink>` element back to the homepage it appears to mount the components on the page multiple times but also doesn't update the state on other elements properly.

**Comment by TylerBarnes** [comment] 2019-05-11 23:23
@NikkiGom that's super weird. I haven't seen that before. I'll have to reproduce locally to debug. Do you know if there's a way to download a codesandbox and run it locally?

@andrwrbnsn that sounds like a different issue. Lets move discussion to #88

**Comment by lacson17** [comment] 2019-05-17 20:04
Can confirm, I am also experiencing the same issues that @NikkiGom is facing. Content overlaps while the Cover transition is in progress, and clears as soon as the transition is over. Has anyone found a solution for this?

**Comment by TylerBarnes** [comment] 2019-05-17 20:30
Maybe trying an older version of TL might make it work until I have time to fix the issue. I've been wanting to work on this but I've been crazy busy

**Comment by dumblole** [comment] 2019-05-19 19:39
Same here as well

**Comment by dumblole** [comment] 2019-05-20 09:43
Found the source for https://github.com/opeah/peintagone the peintagone website and it uses the 1.12.2 version which still doesn't work for me. So I'm wondering if it has to do with something else.

**Comment by xurxe** [comment] 2019-05-25 15:30
I just started using AniLink today (version 1.12.4) and I have the exact same issue!

**Comment by xurxe** [comment] 2019-05-25 16:23
Went through and tested older releases; 1.9.1 --> no issue. 1.9.2 --> issue. So sticking with 1.9.1. for now :)

**Comment by TylerBarnes** [comment] 2019-05-28 00:22
Thanks for testing them out @xurxe ! Glad you found a version that's working for you. 
I've still been too busy to fix this but my plan is to get to it this week.

**Comment by trickydisco78** [comment] 2019-06-03 09:27
I have this exact same issue. Page content stays from the previous page until the page transition has happened

https://lucid-dijkstra-d9d36c.netlify.com

**Comment by Anahkiasen** [comment] 2019-07-06 14:22
Having the same issue on 1.12

**Comment by slashncode** [comment] 2019-07-18 13:48
The issue can be fixed by re-adding the deleted line from commit [9d69a8e](https://github.com/TylerBarnes/gatsby-plugin-transition-link/commit/9d69a8e13557c5c0459ef7c05452da0287c0f128)
but may introduce you to the bug @TylerBarnes fixed
(which I couldn't replicate locally, it seems that the next commit [6654337](https://github.com/TylerBarnes/gatsby-plugin-transition-link/commit/6654337bc43a1466b5cd841da553cd7f23ed1a93) fixed it instead of [9d69a8e](https://github.com/TylerBarnes/gatsby-plugin-transition-link/commit/9d69a8e13557c5c0459ef7c05452da0287c0f128)?).

Still can't find the reason why this is happening, the peintagone & example sites are ok ..

**Comment by sangeet** [comment] 2019-09-03 21:41
Donwgrading to older version fixed the issue. I hope this gets fixed soon. Makes using cover downright ugly in many cases.

**Comment by ajz003** [comment] 2019-12-12 07:49
I'm also having the same issue. Using 1.9.1 works though...

**Closed** 2019-12-16 20:53 UTC

**Comment by TylerBarnes** [comment] 2019-12-16 21:00
Ok, so this took far too long for me to fix. Apologies for that!!
A fix is published in `gatsby-plugin-transition-link@1.17.6`.

The original reason this bug was unintentionally introduced was to prevent bugs if someone pressed the back button during the cover transition. That's no longer necessary since I've disabled the back button during any transition in a later release.

If anyone is still having this problem after updating please let me know and reopen the issue.
