### ISSUE TITLE
TypeError: _ref2 is undefined in TransitionLink

### ISSUE THREAD

**Issue by shivamsingha** [TylerBarnes/gatsby-plugin-transition-link#177] opened 2020-01-08 05:34 UTC
I'm using the react-spring example and I get this error:
```js
./node_modules/gatsby-plugin-transition-link/components/TransitionLink.js/</TransitionLink</<
node_modules/gatsby-plugin-transition-link/components/TransitionLink.js:60

  57 |   },
  58 |   __self: this
  59 | }, function (_ref2) {
> 60 |   var disableAnimation = _ref2.disableAnimation,
  61 |       context = (0, _objectWithoutPropertiesLoose2.default)(_ref2, ["disableAnimation"]);
  62 |   return _react.default.createElement(_gatsby.Link, (0, _extends2.default)({
  63 |     style: style,
```

Here's my code:
```jsx
const SpringComp = ({ children }) => (
  <TransitionState>
    {({ transitionStatus, exit, entry }) => {
      const mount = ['entering', 'entered'].includes(transitionStatus)
      const seconds = mount ? entry.length : exit.length

      return (
        <Spring
          to={{
            transform: `translateY(${mount ? 0 : '100px'})`,
            opacity: mount ? 1 : 0,
          }}
          config={{
            duration: seconds * 1000,
          }}
        >
          {children}
        </Spring>
      )
    }}
  </TransitionState>
)
```

```jsx
const SpringLink = ({ to, children }) => (
  <TransitionLink to={to} exit={{ length: 1 }} entry={{ length: 1 }}>
    {children}
  </TransitionLink>
)
```

**Comment by meesrutten** [comment] 2020-01-14 08:55
I have the same issue.
Just created a fresh Gatsby project, followed the installation guide and tried to add some of the examples but all gave this error:
`TypeError: Cannot read property 'disableAnimation' of undefined
(anonymous function)
node_modules/gatsby-plugin-transition-link/components/TransitionLink.js:60
`

**Comment by shivamsingha** [comment] 2020-01-14 14:28
`gatsby clean` doesn't solve my problem.

**Comment by MrWhiteNoisee** [comment] 2020-01-15 05:09
Also having the same issue as well with a fresh build of Gatsby.

**Comment by DRD161** [comment] 2020-01-28 16:44
Same here. Like others mentioned I am using Gatsby along with styled components and followed the installation guide with no luck thus far. Hopefully this gets resolved soon so I can get some simple page transitions going.

**Comment by AndreBClark** [comment] 2020-02-11 05:55
Same issue, build fails on my blog post using markdown during production build `gatsby build`. 
 - `gatsby clean` doesn't help, 
- everything works fine on `gatsby develop`
- I even tried removing any `transitionLink` or `AniLink` components on that template .

**using:**
gatsby 2.19.12
gatsby-plugin-transition-link 1.17.7
gsap 3.1.1
styled components 5.0.1
```shell
success run queries - 66.739s - 12/12 0.18/s
11:45:30 AM: failed Building static HTML for pages - 7.251s
11:45:30 AM: error Building static HTML failed for path "/colorable-color-contrast-tool/"
11:45:30 AM:   58 |     __self: this
11:45:30 AM:   59 |   }, function (_ref2) {
11:45:30 AM: > 60 |     var disableAnimation = _ref2.disableAnimation,
11:45:30 AM:      |                                  ^
11:45:30 AM:   61 |         context = (0, _objectWithoutPropertiesLoose2.default)(_ref2, ["disableAnimation"]);
11:45:30 AM:   62 |     return _react.default.createElement(_gatsby.Link, (0, _extends2.default)({
11:45:30 AM:   63 |       style: style,
11:45:30 AM: 
11:45:30 AM:   WebpackError: TypeError: Cannot read property 'disableAnimation' of undefined
11:45:30 AM:   
11:45:30 AM:   - TransitionLink.js:60 Object.children
11:45:30 AM:     node_modules/gatsby-plugin-transition-link/components/TransitionLink.js:60:3    4
```

additional context:
- my gatsby site's [repo](https://github.com/AndreBClark/cosmicdivision)
- my [package.json file](https://github.com/AndreBClark/cosmicdivision/blob/master/package.json)
- a markdown file with the netlify [build log](https://github.com/AndreBClark/cosmicdivision/blob/master/_ref2.md)

**Comment by TylerBarnes** [comment] 2020-02-13 21:37
🤔 does that solve the problem for anyone else with this issue?
I haven't had time to work on TL lately :( 

If the issue is that TL isn't in gatsby-config, we should throw a more useful error.

**Comment by DRD161** [comment] 2020-02-13 21:39
In my case I did have it in gatsby-config :/

**Comment by TylerBarnes** [comment] 2020-02-13 21:52
Ok, so I just pulled down the example, upgraded the example's Gatsby packages and ran `gatsby develop` and it runs perfectly. If you're experiencing this issue please try upgrading to the latest `gatsby` and `gatsby-plugin-transition-link`. If that doesn't solve it, please post a minimal reproduction repo so I can pull it down and have a look.

Thanks all!

**Comment by TylerBarnes** [comment] 2020-02-13 21:55
Oh one more thing! I pushed the update in the example repo to master, so you should be able to try it out there as well.

**Comment by shivamsingha** [comment] 2020-02-14 18:11
Please take a look at my [repo](https://github.com/shivamsingha/shivamsingha.github.io/tree/transition-link-test)

I'm kinda new to react so I might just be doing something wrong.

**Comment by TylerBarnes** [comment] 2020-02-14 18:31
Thanks for sharing your repo @shivamsingha! I pulled it down, switched the transition-link branch, and don't have any transition-link specific errors, but you do have a react-spring problem. You're passing `children` to `<Spring>` but it expects to be passed a function.
Change this:
```jsx
            <Spring
              to={{
                transform: `translateY(${mount ? 0 : '100px'})`,
                opacity: mount ? 1 : 0
              }}
              config={{
                duration: seconds * 1000
              }}
            >
              {children}
            </Spring>
```
To this:
```jsx
            <Spring
              to={{
                transform: `translateY(${mount ? 0 : '100px'})`,
                opacity: mount ? 1 : 0
              }}
              config={{
                duration: seconds * 1000
              }}
            >
              {() => children}
            </Spring>
```
If you're still seeing errors related to transition-link, delete your `yarn.lock` and `node_modules`, and the run `yarn` again and you should be good.

**Comment by TylerBarnes** [comment] 2020-02-14 18:36
I believe some of you are experiencing a bug in an outdated version of transition-link. Please upgrade to the latest version. I'm going to close this issue, but feel free to comment here if you need more help.

**Comment by shivamsingha** [comment] 2020-02-14 18:36
I changed `{children}` to 
```js
{() => <>{children}</>}
```
But now the animation doesn't work properly anymore. So I guess I can't do it the way I'm trying to.
Thanks for your help.

**Closed by TylerBarnes** 2020-02-14 18:36 UTC
Labels: waiting for repro

**Comment by TylerBarnes** [comment] 2020-02-14 18:41
@shivamsingha , you'll need to read more about how `react-spring` works. The function you pass to it receives props from the Spring component that you need to wire up to your components. Check the example I posted above or read the `react-spring` docs. I believe [LevelUpTuts](https://www.youtube.com/user/LevelUpTuts/search?query=react-spring) has a good react-spring course as well. That's off topic here though, so you'll need to do some learning elsewhere. Hopefully that helps get you unstuck tho!
